from enum import Enum


class Vec2i:
    x: int = ...
    y: int = ...


class ActionType(Enum): ...


class ObjectType(Enum): ...


class Node:
    def __init__(self) -> None: ...
    def get_name(self) -> str: ...
    def get_position(self) -> Vec2i: ...
    def get_type(self) -> int: ...
    def get_id(self) -> int: ...
    def get_option(self, option_index: int) -> str: ...
    def _do_action(self, id: int, action_type: ActionType) -> None: ...


class Entity:
    def __init__(self) -> None: ...
    def get_name(self) -> str: ...
    def get_position(self) -> Vec2i: ...
    def get_type(self) -> int: ...
    def get_id(self) -> int: ...
    def _do_action(self, id: int, action_type: ActionType) -> None: ...
    def get_combat_level(self) -> int: ...


class GroundItem:
    def __init__(self) -> None: ...
    def get_name(self) -> str: ...
    def get_price(self) -> int: ...
    def get_position(self) -> Vec2i: ...
    def get_type(self) -> int: ...
    def get_id(self) -> int: ...

    def _do_action(
        self, id: int, x: int, y: int, action_type: ActionType
    ) -> None: ...


def get_hero_position() -> Vec2i: ...
def get_entities(object_type: ObjectType) -> list: ...
